language: python
python:
  - 3.6
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - python tests.py
after_success:
  - codecov # submit coverage