version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3-stretch
    steps:
      - checkout
      - run:
          name: Install Python dependencies in a venv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv

  test:
    docker:
      - image: circleci/python:3.6.3-stretch
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            . venv/bin/activate
            python tests.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      